version: "3"

services:
  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins
    restart: always
    volumes:
      - jenkins-data:/var/jenkins_home
    ports:
      - "8080:8080"
    
  nginx:
    image: nginx:1.20.0
    container_name: nginx
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "test123456"
    volumes:
      - nginx-data:/usr/share/nginx/html
    ports:
      - "8090:80"
    

volumes:
  jenkins-data: {}
  nginx-data: {}

                   
